name: kmdr
summary: CLI client for explaning shell commands
link: https://kmdr.sh/
version: "0.2.0"
locale: en
options:
  - short:
      - "-l"
    long:
      - "--language"
    summary: Set the language
    expectsArg: true
subcommands:
  - name: explain
    summary: Explain a command
    aliases:
      - e
    options:
      - short:
          - "-h"
        long:
          - "--highlight"
    summary: Show syntax highlighting
  - name: config
    summary: Configure kmdr on this computer
    aliases:
      - c
